# Generated by Django 6.0.7 on 2026-07-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('artist', models.CharField(blank=True, db_index=True, max_length=255)),
                ('platinum_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('language', models.CharField(blank=True, default='', max_length=64)),
                ('genre', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'artist'],
                'indexes': [models.Index(fields=['title', 'artist'], name='songs_song_title_aced60_idx')],
            },
        ),
    ]
