# Generated by Django 6.0.7 on 2026-07-31 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platinum_number', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('artist', models.CharField(blank=True, default='', max_length=255)),
                ('suggested_number', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('fixed', 'Fixed'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='songs.song')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
