# Generated by Django 6.0.7 on 2026-07-31 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_songreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='songreport',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='songreport',
            name='song',
            field=models.ForeignKey(blank=True, help_text='Linked song (null if already deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='songs.song'),
        ),
    ]
