# Generated by Django 6.0.7 on 2026-07-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_songreport_admin_notes_alter_songreport_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('role', models.CharField(blank=True, default='guest', max_length=20)),
                ('path', models.CharField(blank=True, default='', max_length=120)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
