# Generated by Django 6.0.7 on 2026-07-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_visitorpresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('letter', models.CharField(blank=True, default='ALL', max_length=8)),
                ('category', models.CharField(blank=True, default='ALL', max_length=32)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', '-created_at'], name='songs_searc_query_5bcc75_idx')],
            },
        ),
    ]
