# Generated by Django 6.0.7 on 2026-07-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_searchevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='songreport',
            index=models.Index(fields=['status', '-created_at'], name='songs_songr_status_9a0e82_idx'),
        ),
    ]
